version: '3.8'
services:
  eso-server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    image: eso-server-image
    container_name: eso-server
    ports:
      - 80:80
    command: npm run start:prod