version: '3.8'
services:
  eso-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: eso-server-image
    container_name: eso-server
    env_file: .env.production
    restart: unless-stopped