version: '3.8'
services:
  eso-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: eso-server-image
    container_name: eso-server
    env_file: .env.production
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    #   - /usr/src/app/build
    ports:
      - 80:80
    command: npm run start:prod:local